export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';

export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';

export const CHANGE_CURRENT_USER = 'CHANGE_CURRENT_USER';

export const CHANGE_CURRENT_USER_ID = 'CHANGE_CURRENT_USER_ID';

export const TAB_CACHE_REMOVED = 'TAB_CACHE_REMOVED';

export const TAB_CACHE_ADDED = 'TAB_CACHE_ADDED';

export const CHANGE_CURRENT_ENTITY = 'CHANGE_CURRENT_ENTITY';

export const CHANGE_CURRENT_ENTITY_ID = 'CHANGE_CURRENT_ENTITY_ID';


